logging:
  config: classpath:logback-spring.xml
server:
  port: 8081
spring:
  application:
    name: rpc-service-consumer

zns:
  client:
      zk:
        root: /rpc
        addr: localhost:2181
        switch: true
      api:
        package: cn.edu.nju.service.api
  cluster:
        strategy: Polling