logging:
  config: classpath:logback-spring.xml
server:
  port: 8082
spring:
  application:
    name: rpc-service-provider

rpc:
  server:
      zk:
        root: /rpc
        addr: localhost:2181
        switch: true
  network:
      port: 8888